---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    purpose: prometheus-store
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volumes/prometheus-store
    server: 192.168.0.50
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
  labels:
    purpose: prometheus-wal
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volumes/prometheus-wal
    server: 192.168.0.50
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0005
  labels:
    purpose: terraria-saves
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volumes/game-saves/terraria-worlds
    server: 192.168.0.50
