---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria-large-journey-deployment
  labels:
    app: terraria
    purpose: provide-terraria-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria
      purpose: provide-terraria-server
  template:
    metadata:
      labels:
        app: terraria
        purpose: provide-terraria-server
    spec:
      containers:
      - name: terraria
        image: markthemarkest/terraria-server-configured
        volumeMounts:
          - name: tshock-config-volume
            mountPath: "/tshock/tshock/config-defaults.json"
            subPath: tshock-config.json
          - name: config-volume
            mountPath: "/var/tshock/server-config.txt"
            subPath: server-config.txt
          - name: save-volume
            mountPath: "/var/terraria/worlds"
        ports:
        - containerPort: 7777
      volumes:
        - name: tshock-config-volume
          configMap:
            name: tshock-large-journey-cm
        - name: config-volume
          configMap:
            name: terraria-large-journey-cm
        - name: save-volume
          persistentVolumeClaim:
            claimName: terraria-save-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-save-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: slow
  selector:
    matchLabels:
      purpose: "terraria-saves"
---
kind: Service
apiVersion: v1
metadata:
  name: terraria-large-journey-service
spec:
  type: NodePort
  selector:
    app: terraria
    purpose: provide-terraria-server
  ports:
  - name: terraria
    protocol: TCP
    port: 7777
    nodePort: 31001
