---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
    purpose: monitor-household-stuff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      purpose: monitor-household-stuff
  template:
    metadata:
      labels:
        app: prometheus
        purpose: monitor-household-stuff
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
          - name: prometheus-store
            mountPath: "/prometheus/data"
        ports:
        - containerPort: 9090
      volumes:
        - name: config-volume
          configMap:
           name: prometheus-cm
        - name: prometheus-store
          persistentVolumeClaim:
            claimName: prometheus-claim
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
    purpose: monitor-household-stuff
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090
  externalIPs:
    - 192.168.0.60
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-external-service
spec:
  selector:
    service: prometheus-service
    purpose: monitor-household-stuff
  type: ExternalName
  externalName: home.prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
