apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
