---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
    purpose: monitor-household-stuff
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090
