{
 "title": "Primary",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pi Memory Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active / node_memory_MemTotal * 100"
    }
   ]
  },
  {
   "title": "Laptop Memory Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes / node_memory_MemFree_bytes * 100"
    }
   ]
  },
  {
   "title": "Laptop Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_hwmon_temp_celsius" }
   ]
  },
  {
   "title": "Pi Temps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temp" }
   ]
  }
 ]
}