---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
    purpose: visualize-household-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      purpose: visualize-household-metrics
  template:
    metadata:
      labels:
        app: grafana
        purpose: visualize-household-metrics
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        volumeMounts:
          - name: datasource-config-volume
            mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
            subPath: datasources.yml
          - name: hw-dash-config-volume
            mountPath: /var/lib/grafana/dashboards/hardware.json
            subPath: hardware.json
          - name: k8s-dash-config-volume
            mountPath: /var/lib/grafana/dashboards/kubernetes.json
            subPath: kubernetes.json
          - name: dashboard-providers-volume
            mountPath: /etc/grafana/provisioning/dashboards/dashboard-providers.yaml
            subPath: dashboard-providers.yml
        ports:
        - containerPort: 3000
      volumes:
        - name: datasource-config-volume
          configMap:
           name: grafana-datasource-cm
        - name: hw-dash-config-volume
          configMap:
           name: grafana-hw-cm
        - name: k8s-dash-config-volume
          configMap:
           name: grafana-k8s-cm
        - name: dashboard-providers-volume
          configMap:
           name: grafana-dashboard-providers-cm
---
kind: Service
apiVersion: v1
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
    purpose: visualize-household-metrics
  ports:
  - name: grafanaui
    protocol: TCP
    port: 3000
    targetPort: 3000
apiVersion: v1
---
kind: Service
apiVersion: v1
metadata:
  name: grafana-service-external
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000
  selector:
    app: grafana
    purpose: visualize-household-metrics
