---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
    purpose: visualize-household-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      purpose: visualize-household-metrics
  template:
    metadata:
      labels:
        app: grafana
        purpose: visualize-household-metrics
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        volumeMounts:
          - name: datasource-config-volume
            mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
            subPath: datasources.yml
          - name: grafana-dashboards-volume
            mountPath: /var/lib/grafana/dashboards/hardware.json
            subPath: hardware.json
          - name: grafana-dashboards-volume
            mountPath: /var/lib/grafana/dashboards/kubernetes.json
            subPath: kubernetes.json
          - name: grafana-dashboards-volume
            mountPath: /var/lib/grafana/dashboards/gaming-desktop.json
            subPath: gaming-desktop.json
          - name: dashboard-providers-volume
            mountPath: /etc/grafana/provisioning/dashboards/dashboard-providers.yaml
            subPath: dashboard-providers.yml
          - name: grafana-dashboards-volume
            mountPath: /var/lib/grafana/dashboards/pandora.json
            subPath: pandora.json
          - name: grafana-dashboards-volume
            mountPath: /var/lib/grafana/dashboards/dora.json
            subPath: dora.json
          - name: grafana-dashboards-volume
            mountPath: /var/lib/grafana/dashboards/mark-laptop-windows.json
            subPath: mark-laptop-windows.json
        ports:
        - containerPort: 3000
      volumes:
        - name: datasource-config-volume
          configMap:
            name: grafana-datasource-cm
        - name: grafana-dashboards-volume
          configMap:
            name: grafana-dashboards-cm
        - name: dashboard-providers-volume
          configMap:
            name: grafana-dashboard-providers-cm
