---
kind: Service
apiVersion: v1
metadata:
  name: grafana-service-external
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000
  selector:
    app: grafana
    purpose: visualize-household-metrics
