---
kind: Service
apiVersion: v1
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
    purpose: visualize-household-metrics
  ports:
  - name: grafanaui
    protocol: TCP
    port: 3000
    targetPort: 3000
apiVersion: v1
