{
 "title": "Gaming Desktop",
 "description": "A dashboard for monitoring a Windows Desktop/Gaming PC. Using Prometheus, wmi_exporter, and OhmGraphite.",
 "time": { "from": "2020-11-14T22:41:56.959Z", "to": "2020-11-15T09:34:29.895Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host",
    "query": "label_values(wmi_system_system_up_time, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Current Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((avg without (cpu) (sum(irate(windows_cpu_time_total{mode!=\"idle\",job=\"mark-desktop\"}[5m])) by (mode)) / 8)* 100)"
    }
   ]
  },
  {
   "title": "GPU Core Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ohm_gpunvidia_load_percent{job=\"mark-desktop\"})"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{job=\"mark-desktop\"} - windows_os_physical_memory_free_bytes{job=\"mark-desktop\"}) / (windows_cs_physical_memory_bytes{job=\"mark-desktop\"}) * 100"
    },
    { "expr": "windows_" }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_total{job=\"mark-desktop\"}[1m])) > 1)* 8"
    },
    {}
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ohm_cpu_celsius{job=\"mark-desktop\"})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_celsius{job=\"mark-desktop\"}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\",job=\"mark-desktop\"}) - sum(windows_logical_disk_free_bytes{volume!~\"Harddisk.*\",job=\"mark-desktop\"})) / sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\",job=\"mark-desktop\"}) * 100"
    }
   ]
  },
  {
   "title": "GPU Fan %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_control_percent{job=\"mark-desktop\"}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg without (cpu) (sum(irate(windows_cpu_time_total{mode!=\"idle\",job=\"mark-desktop\"}[5m])) by (mode)) / 8)* 100"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_gpunvidia_load_percent{job=\"mark-desktop\"}"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{job=\"mark-desktop\"} - windows_os_physical_memory_free_bytes{job=\"mark-desktop\"})"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=\"mark-desktop\"}"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "ohm_gpunvidia_bytes{sensor=\"GPU Memory Used\",job=\"mark-desktop\"} / 1000000"
    },
    {
     "expr": "ohm_gpunvidia_bytes{sensor=\"GPU Memory Total\",job=\"mark-desktop\"} / 1000000"
    }
   ]
  },
  {
   "title": "Clock Speeds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "MHz" }
   ],
   "targets": [
    {
     "expr": "ohm_gpunvidia_hertz{job=\"mark-desktop\"} / 1000000"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ohm_gpunvidia_watts{job=\"mark-desktop\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_received_total{job=\"mark-desktop\"}[1m])) by (instance) > 1)* 8"
    },
    {
     "expr": "(sum(irate(windows_net_bytes_sent_total{job=\"mark-desktop\"}[1m])) by (instance) > 1)* 8"
    }
   ]
  },
  {
   "title": "Bandwidth Usage (Hourly)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{job=\"mark-desktop\"}[1h]))"
    },
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{job=\"mark-desktop\"}[1h]))"
    }
   ]
  },
  {
   "title": "Bandwidth Usage (Daily)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{job=\"mark-desktop\"}[1d]))"
    },
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{job=\"mark-desktop\"}[1d]))"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Free Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{volume !~\"HarddiskVolume.+\",job=\"mark-desktop\"}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_split_ios_total{volume !~\"HarddiskVolume.+\",job=\"mark-desktop\"}[1m])"
    }
   ]
  },
  {
   "title": "Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(windows_logical_disk_write_bytes_total{volume !~\"HarddiskVolume.+\",job=\"mark-desktop\"}[1m])"
    },
    {
     "expr": "irate(windows_logical_disk_read_bytes_total{volume !~\"HarddiskVolume.+\",job=\"mark-desktop\"}[1m])"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "CPU Temperatures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_celsius{sensor =~\"CPU Core #[0-9]+\",job=\"mark-desktop\"}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ohm_gpunvidia_celsius{job=\"mark-desktop\"}"
    }
   ]
  },
  {
   "title": "GPU Fan %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ohm_gpunvidia_control_percent{job=\"mark-desktop\"}"
    }
   ]
  },
  {
   "title": "SSD Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ohm_hdd_celsius{job=\"mark-desktop\"}"
    }
   ]
  },
  { "title": "Extended CPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Clock Speeds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "none", "label": "MHz" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_hertz{job=\"mark-desktop\"} / 1000000"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_watts{job=\"mark-desktop\"}"
    }
   ]
  },
  { "title": "Processes / Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "# of Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_os_processes{job=\"mark-desktop\"}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(windows_service_state{job=\"mark-desktop\"}) by (state)"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(windows_service_status{job=\"mark-desktop\"}) by (status)"
    }
   ]
  }
 ]
}