{
 "title": "Server Hardware",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Pi CPU Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{job=\"kubernetes-raspberries\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Pi Memory Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active / (node_memory_Active + node_memory_MemTotal) * 100"
    }
   ]
  },
  {
   "title": "Laptop Memory Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_Active_bytes" },
    { "expr": "node_memory_MemTotal_bytes " }
   ]
  },
  {
   "title": "Laptop Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_hwmon_temp_celsius" }
   ]
  },
  {
   "title": "Pi Temps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temp" }
   ]
  }
 ]
}