{
 "title": "Kubernetes cluster monitoring (via Prometheus) 2",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network I/O pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster CPU usage (1m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster filesystem usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System services CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System services memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{systemd_service_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (systemd_service_name)",
       "legendFormat": "{{ systemd_service_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
       "legendFormat": "-> {{ pod_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
       "legendFormat": "<- {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
       "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
       "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    }
   ]
  }
 ]
}