{
 "title": "New Linux Desktop",
 "description": "A dashboard for monitoring a Linux Desktop/Gaming PC. Using Prometheus, node_exporter.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(wmi_system_system_up_time, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((avg without (cpu) (sum(irate(node_cpu_seconds_total{mode!=\"idle\",job=\"duke\"}[5m])) by (mode)) / 4)* 100)"
    }
   ]
  },
  {
   "title": "GPU Core Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{job=\"duke\"})"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"duke\"} - node_memory_MemFree_bytes{job=\"duke\"}  - node_memory_Cached_bytes{job=\"duke\"}) / (node_memory_MemTotal_bytes{job=\"duke\"} )) * 100"
    },
    { "expr": "windows_" }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{job=\"duke\"}[1m])) > 1)* 8"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\",job=\"duke\"})"
    },
    {}
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_nct6775_656\", instance=\"192.168.0.8:9100\", job=\"duke\", sensor=\"temp2\"}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{volume!~\"Harddisk.*\",job=\"duke\"}) - sum(node_filesystem_avail_bytes{volume!~\"Harddisk.*\",job=\"duke\"})) / sum(node_filesystem_size_bytes{volume!~\"Harddisk.*\",job=\"duke\"}) * 100"
    }
   ]
  },
  {
   "title": "GPU Fan %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"0000:07:00_0_0000:08:00_0\",job=\"duke\"}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg without (cpu) (sum(irate(node_cpu_seconds_total{mode!=\"idle\",job=\"duke\"}[5m])) by (mode)) / 4)* 100"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{job=\"duke\"}"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"duke\"} - node_memory_MemFree_bytes{job=\"duke\"}) - node_memory_Cached_bytes{job=\"duke\"}"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"duke\"}"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "GPU Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{job=\"duke\"}"
    },
    {
     "expr": "DCGM_FI_DEV_FB_FREE{job=\"duke\"} + DCGM_FI_DEV_FB_USED{job=\"duke\"}"
    }
   ]
  },
  {
   "title": "Clock Speeds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "MHz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{job=\"duke\"}"
    },
    {
     "expr": "DCGM_FI_DEV_MEM_CLOCK{job=\"duke\"}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{chip=\"0000:07:00_0_0000:08:00_0\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{job=\"duke\"}[1m])) by (instance) > 1)* 8"
    },
    {
     "expr": "(sum(irate(node_network_transmit_bytes_total{job=\"duke\"}[1m])) by (instance) > 1)* 8"
    }
   ]
  },
  {
   "title": "Bandwidth Usage (Hourly)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{job=\"duke\"}[1h]))"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{job=\"duke\"}[1h]))"
    }
   ]
  },
  {
   "title": "Bandwidth Usage (Daily)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{job=\"duke\"}[1d]))"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{job=\"duke\"}[1d]))"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Free Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{volume !~\"HarddiskVolume.+\",job=\"duke\"}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_now{volume !~\"HarddiskVolume.+\",job=\"duke\"}[1m])"
    }
   ]
  },
  {
   "title": "Read/Write Seconds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{volume !~\"HarddiskVolume.+\",job=\"duke\"}[1m])"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{volume !~\"HarddiskVolume.+\",job=\"duke\"}[1m])"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "CPU Temperatures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_nct6775_656\", instance=\"192.168.0.8:9100\", job=\"duke\", sensor=\"temp2\"}"
    }
   ]
  },
  {
   "title": "Fan revolutions per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_nct6775_656\",job=\"duke\"}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"0000:07:00_0_0000:08:00_0\",job=\"duke\",sensor=\"temp2\"}"
    }
   ]
  },
  {
   "title": "GPU Fan %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"0000:07:00_0_0000:08:00_0\",job=\"duke\"}"
    }
   ]
  },
  {
   "title": "SSD Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value{job=\"duke\"}"
    }
   ]
  },
  { "title": "Extended CPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Clock Speeds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "none", "label": "MHz" }
   ],
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{job=\"duke\"} / 1000000"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{job=\"duke\"}"
    }
   ]
  },
  { "title": "Processes / Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "# of Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{job=\"duke\"}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_systemd_units{job=\"duke\"}) by (state)"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{job=\"duke\"}) by (status)"
    }
   ]
  }
 ]
}