{
 "title": "Pandora",
 "description": "A dashboard for monitoring a Windows PC. Using Prometheus, wmi_exporter, and OhmGraphite.",
 "time": { "from": "2020-12-10T23:36:58.499Z", "to": "2020-12-10T23:46:58.499Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host",
    "query": "label_values(wmi_system_system_up_time, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Current Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((avg without (cpu) (sum(irate(windows_cpu_time_total{mode!=\"idle\",job=\"pandora\"}[5m])) by (mode)) / 8)* 100)"
    }
   ]
  },
  {
   "title": "GPU Core Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ohm_gpunvidia_load_percent{job=\"pandora\"})"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{job=\"pandora\"} - windows_os_physical_memory_free_bytes{job=\"pandora\"}) / (windows_cs_physical_memory_bytes{job=\"pandora\"}) * 100"
    },
    { "expr": "windows_" }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_total{job=\"pandora\"}[1m])) > 1)* 8"
    },
    {}
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ohm_cpu_celsius{job=\"pandora\"})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_celsius{job=\"pandora\"}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\",job=\"pandora\"}) - sum(windows_logical_disk_free_bytes{volume!~\"Harddisk.*\",job=\"pandora\"})) / sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\",job=\"pandora\"}) * 100"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg without (cpu) (sum(irate(windows_cpu_time_total{mode!=\"idle\",job=\"pandora\"}[5m])) by (mode)) / 8)* 100"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_gpunvidia_load_percent{job=\"pandora\"}"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(windows_cs_physical_memory_bytes{job=\"pandora\"} - windows_os_physical_memory_free_bytes{job=\"pandora\"})"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=\"pandora\"}"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Clock Speeds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "MHz" }
   ],
   "targets": [
    {
     "expr": "ohm_gpunvidia_hertz{job=\"pandora\"} / 1000000"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_received_total{job=\"pandora\"}[1m])) by (instance) > 1)* 8"
    },
    {
     "expr": "(sum(irate(windows_net_bytes_sent_total{job=\"pandora\"}[1m])) by (instance) > 1)* 8"
    }
   ]
  },
  {
   "title": "Bandwidth Usage (Hourly)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{job=\"pandora\"}[1h]))"
    },
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{job=\"pandora\"}[1h]))"
    }
   ]
  },
  {
   "title": "Bandwidth Usage (Daily)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{job=\"pandora\"}[1d]))"
    },
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{job=\"pandora\"}[1d]))"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Free Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{volume !~\"HarddiskVolume.+\",job=\"pandora\"}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_split_ios_total{volume !~\"HarddiskVolume.+\",job=\"pandora\"}[1m])"
    }
   ]
  },
  {
   "title": "Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(windows_logical_disk_write_bytes_total{volume !~\"HarddiskVolume.+\",job=\"pandora\"}[1m])"
    },
    {
     "expr": "irate(windows_logical_disk_read_bytes_total{volume !~\"HarddiskVolume.+\",job=\"pandora\"}[1m])"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "CPU Temperatures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_celsius{sensor =~\"CPU Core #[0-9]+\",job=\"pandora\"}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ohm_gpunvidia_celsius{job=\"pandora\"}"
    }
   ]
  },
  { "title": "Extended CPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Clock Speeds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none", "label": "MHz" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_hertz{job=\"pandora\"} / 1000000"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_watts{job=\"pandora\"}"
    }
   ]
  },
  { "title": "Processes / Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "# of Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_os_processes{job=\"pandora\"}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(windows_service_state{job=\"pandora\"}) by (state)"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(windows_service_status{job=\"pandora\"}) by (status)"
    }
   ]
  }
 ]
}