---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    purpose: provide-mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      purpose: provide-mysql-db
  template:
    metadata:
      labels:
        app: mysql
        purpose: provide-mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        volumeMounts:
          - name: mysql-store
            mountPath: "/var/lib/mysql"
        ports:
        - containerPort: 8080
      volumes:
        - name: mysql-store
          persistentVolumeClaim:
            claimName: mysql-claim
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
    purpose: provide-mysql-db
  ports:
  - name: promui
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
  selector:
    matchLabels:
      purpose: "mysql-store"
