---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria-deployment
  labels:
    app: terraria
    purpose: provide-terraria-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria
      purpose: provide-terraria-server
  template:
    metadata:
      labels:
        app: terraria
        purpose: provide-terraria-server
    spec:
      containers:
      - name: terraria
        image: markthemarkest/terraria-server
        command: ["mono"]
        args: ["--server", "--gc=sgen", "-O=all", "TerrariaServer.exe", "-autocreate", "1"]
        volumeMounts:
          - name: config-volume
            mountPath: "/tshock/server-config.txt"
            subPath: server-config.txt
        ports:
        - containerPort: 7777
      volumes:
        - name: config-volume
          configMap:
            name: terraria-cm
---
kind: Service
apiVersion: v1
metadata:
  name: terraria-service
spec:
  type: NodePort
  selector:
    app: terraria
    purpose: provide-terraria-server
  ports:
  - name: promui
    protocol: TCP
    port: 7777
    targetPort: 7777
