---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-save-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: slow
  selector:
    matchLabels:
      purpose: "terraria-saves"
