---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    purpose: provide-mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      purpose: provide-mysql-db
  template:
    metadata:
      labels:
        app: mysql
        purpose: provide-mysql-db
    spec:
      containers:
      - name: mysql
        image: linuxserver/mariadb
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: keepItSecret
          - name: PUID
            value: '65534'
          - name: PGID
            value: '65534'
        volumeMounts:
          - name: mysql-store
            mountPath: "/config"
        ports:
        - containerPort: 3306
      volumes:
        - name: mysql-store
          persistentVolumeClaim:
            claimName: mysql-claim
