---
kind: Service
apiVersion: v1
metadata:
  name: mysql-service-external
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30306
  selector:
    app: mysql
    purpose: provice-mysql-server

